theme: jekyll-theme-cayman
title: Mod DJI Fly iOS v1.4.0
description: Auto-enabled FCC for Mavic Air 2, Air2S, Mini2 & Mavic Mini, + Airsense (Mavic Air 2 3W Model)
github:
    is_project_page: false


# header background
header-img: "/assets/img/bg.jpg"


current_version: "v1.4.0"

#URLs
dropbox_url:            "https://www.dropbox.com/s/uqeau82xmsz7mme/Mod_DJI_Fly_v1.4.0_unsig.ipa?dl=1"
paypal_url:             "https://paypal.me/fccdjifly/15GBP"
cydia_url:              "cydia://url/https://cydia.saurik.com/api/share#?source=https://cydia.akemi.ai/"
jailbreak_install_url:  "itms-services://?action=download-manifest&amp;url=https://dl.dropboxusercontent.com/s/44yr0mizt4vhcgx/v1.4.0.plist"
appbox_url:             "https://tiny.app.link/bj10sx6TLfb"


# email stuff
email:
  id: 'gb160@protonmail.com?subject=Mod DJI Fly'
  href: 'mailto:'
  title: 'Email Me'
  fa-icon: 'fa-envelope-square'
