theme: jekyll-theme-cayman

title: Mod DJI Fly iOS v1.4.0

description: Unlock full FCC power to increase signal strength and range considerably<br><br>Unlock 5.8 GHz band in restricted locations<br><br>Unlock Airsense (ADSB) on Mavic Air 2 drones

github:
    is_project_page: false


# header background
header-img: "/assets/img/bg.jpg"



#URLs
url_dropbox:              "https://www.dropbox.com/s/uqeau82xmsz7mme/Mod_DJI_Fly_v1.4.0_unsig.ipa?dl=1"
url_paypal:               "https://paypal.me/fccdjifly/15GBP"
url_cydia:                "cydia://url/https://cydia.saurik.com/api/share#?source=https://cydia.akemi.ai/"
url_jailbreak_install:    "itms-services://?action=download-manifest&amp;url=https://dl.dropboxusercontent.com/s/44yr0mizt4vhcgx/v1.4.0.plist"
url_appbox:               "https://tiny.app.link/bj10sx6TLfb"


#button icons
icon_appbox:              "fas fa-box"
icon_cydia:               "fas fa-plus"
icon_dropbox:             "fab fa-dropbox"
icon_email:               "fas fa-envelope"
icon_guide_flysign:       "fas fa-plane-departure"
icon_guide_installation:  "fas fa-toolbox"
icon_info_purchasing:     "fab fa-paypal"
icon_info_signing:        "fas fa-edit"
icon_jailbreak_install:   "fas fa-arrow-circle-down"
icon_paypal:              "fab fa-paypal"



# email stuff
email:
  id: 'gb160@protonmail.com?subject=Mod DJI Fly'
  href: 'mailto:'
  title: 'Email Me'
  fa-icon: 'fa-envelope-square'
