theme: jekyll-theme-cayman
title: Mod DJI Fly iOS v1.4.0
description: Auto-enabled FCC for Mavic Air 2, Air2S, Mini2 & Mavic Mini, + Airsense (Mavic Air 2 3W Model)
github:
    is_project_page: false

# image:
#     background: pop-bg.jpg

page-img: "/assets/img/bg.jpg"

# social-network-links:
#   email: "gb160@protonmail.com"

current_version: "v1.4.0"
dropbox_url: "https://www.dropbox.com/s/uqeau82xmsz7mme/Mod_DJI_Fly_v1.4.0_unsig.ipa?dl=1"
paypal_url: "https://paypal.me/fccdjifly/15GBP"

# social-network-links:
#   email: "gb160@protonmail.com"
