theme: jekyll-theme-cayman
title: Mod DJI Fly iOS v1.3.1
description: Auto-enabled FCC & Airsense (3W Model) for DJI Mavic Air 2, Auto-enabled FCC for Mini 2 & Mavic Mini
github:
    is_project_page: false
