theme: jekyll-theme-cayman

title: Mod DJI Fly iOS v1.4.3

description: Unlock full FCC power to increase signal strength and range considerably <br><br>Unlock 5.8 GHz band in restricted locations <br><br>Unlock Airsense (ADSB) on supported Mavic Air 2 drones <br><br>Optional Weather Status Notification

github:
    is_project_page: false


# header background
header-img: "/assets/img/bg.jpg"



#URLs
url_dropbox:              "https://www.dropbox.com/s/cqp8vgr2ut9iyct/Mod_DJI_Fly_v1.4.3_unsig.ipa?dl=1"
url_paypal:               "https://paypal.me/fccdjifly/15GBP"
url_cydia:                "cydia://url/https://cydia.saurik.com/api/share#?source=https://cydia.akemi.ai/"
url_jailbreak_install:    "itms-services://?action=download-manifest&amp;url=https://dl.dropboxusercontent.com/s/su5tmggg0cy9yj9/v1.4.3.plist"
url_beta_install:         "itms-services://?action=download-manifest&amp;url=https://dl.dropboxusercontent.com/s/jibberish/v1.4.0.plist"
url_appbox:               "https://tiny.app.link/iwQM6SSjjgb"

#button icons
icon_appbox:              "fas fa-box fa-2x"
icon_cydia:               "fas fa-plus fa-2x"
icon_dropbox:             "fab fa-dropbox fa-2x"
icon_email:               "fas fa-envelope fa-2x"
icon_guide_flysign:       "fas fa-plane-departure fa-2x"
icon_guide_installation:  "fas fa-toolbox fa-2x"
icon_info_purchasing:     "fab fa-paypal fa-2x"
icon_info_signing:        "fas fa-edit fa-2x"
icon_jailbreak_install:   "fas fa-arrow-circle-down fa-2x"
icon_paypal:              "fab fa-paypal fa-2x"
icon_bitcoin:             "fab fa-bitcoin fa-2x"
icon_ethereum:            "fab fa-ethereum fa-2x"
icon_credit_card:         "fas fa-credit-card fa-2x"

anchor_contact-and-support:   "#contact-and-support"

#crypto
url_coinbase:             "https://commerce.coinbase.com/checkout/061da20e-f018-4d8a-be2a-c488ae77a784"

# email stuff
email:
  id: 'gb160@protonmail.com?subject=Mod DJI Fly'
  href: 'mailto:'
  title: 'Email Me'
  fa-icon: 'fa-envelope-square'

