theme: jekyll-theme-cayman
title: Mod DJI Fly iOS v1.4.0
description: Auto-enabled FCC & Airsense (3W Model) for DJI Mavic Air 2, Auto-enabled FCC for Air2S, Mini2 & Mavic Mini
github:
    is_project_page: false
