theme: jekyll-theme-cayman
title: Mod DJI Fly iOS v1.4.0
description: Auto-enabled FCC for Mavic Air 2, Air2S, Mini2 & Mavic Mini, + Airsense (Mavic Air 2 3W Model)
github:
    is_project_page: false


# page-img: "/assets/img/bg.jpg"

social-network-links:
  email: "gb160@protonmail.com"
